package MAV;


/**
* MAV/_SRVStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idls/MAV.idl
* lundi 28 mai 2007 15 h 21 CEST
*/

public class _SRVStub extends org.omg.CORBA.portable.ObjectImpl implements MAV.SRV
{

  public MAV.ResultVote[] listeResultat () throws MAV.SRVPackage.InternalErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listeResultat", true);
                $in = _invoke ($out);
                MAV.ResultVote $result[] = MAV.SRVPackage.ResultSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MAV/SRV/InternalErrorException:1.0"))
                    throw MAV.SRVPackage.InternalErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listeResultat (        );
            } finally {
                _releaseReply ($in);
            }
  } // listeResultat

  public MAV.Candidat[] listeCandidat () throws MAV.SRVPackage.InternalErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listeCandidat", true);
                $in = _invoke ($out);
                MAV.Candidat $result[] = MAV.SRVPackage.CandidatSeqHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MAV/SRV/InternalErrorException:1.0"))
                    throw MAV.SRVPackage.InternalErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listeCandidat (        );
            } finally {
                _releaseReply ($in);
            }
  } // listeCandidat

  public boolean authMAV (int idMAV, int idBV) throws MAV.SRVPackage.InternalErrorException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("authMAV", true);
                $out.write_long (idMAV);
                $out.write_long (idBV);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MAV/SRV/InternalErrorException:1.0"))
                    throw MAV.SRVPackage.InternalErrorExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return authMAV (idMAV, idBV        );
            } finally {
                _releaseReply ($in);
            }
  } // authMAV

  public void authPersonne (int numInsee, String password, int idBV) throws MAV.SRVPackage.BadAuthentificationException, MAV.SRVPackage.AlreadyVoteException, MAV.SRVPackage.InternalErrorException, MAV.SRVPackage.IncorrectBVPersonException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("authPersonne", true);
                $out.write_long (numInsee);
                $out.write_string (password);
                $out.write_long (idBV);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MAV/SRV/BadAuthentificationException:1.0"))
                    throw MAV.SRVPackage.BadAuthentificationExceptionHelper.read ($in);
                else if (_id.equals ("IDL:MAV/SRV/AlreadyVoteException:1.0"))
                    throw MAV.SRVPackage.AlreadyVoteExceptionHelper.read ($in);
                else if (_id.equals ("IDL:MAV/SRV/InternalErrorException:1.0"))
                    throw MAV.SRVPackage.InternalErrorExceptionHelper.read ($in);
                else if (_id.equals ("IDL:MAV/SRV/IncorrectBVPersonException:1.0"))
                    throw MAV.SRVPackage.IncorrectBVPersonExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                authPersonne (numInsee, password, idBV        );
            } finally {
                _releaseReply ($in);
            }
  } // authPersonne

  public boolean vote (int numInsee, String password, int idCandidat, int idBV) throws MAV.SRVPackage.BadAuthentificationException, MAV.SRVPackage.AlreadyVoteException, MAV.SRVPackage.InternalErrorException, MAV.SRVPackage.IncorrectBVPersonException
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("vote", true);
                $out.write_long (numInsee);
                $out.write_string (password);
                $out.write_long (idCandidat);
                $out.write_long (idBV);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MAV/SRV/BadAuthentificationException:1.0"))
                    throw MAV.SRVPackage.BadAuthentificationExceptionHelper.read ($in);
                else if (_id.equals ("IDL:MAV/SRV/AlreadyVoteException:1.0"))
                    throw MAV.SRVPackage.AlreadyVoteExceptionHelper.read ($in);
                else if (_id.equals ("IDL:MAV/SRV/InternalErrorException:1.0"))
                    throw MAV.SRVPackage.InternalErrorExceptionHelper.read ($in);
                else if (_id.equals ("IDL:MAV/SRV/IncorrectBVPersonException:1.0"))
                    throw MAV.SRVPackage.IncorrectBVPersonExceptionHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return vote (numInsee, password, idCandidat, idBV        );
            } finally {
                _releaseReply ($in);
            }
  } // vote

  public void enregistrerVTR (MAV.VTR vtr)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("enregistrerVTR", true);
                MAV.VTRHelper.write ($out, vtr);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                enregistrerVTR (vtr        );
            } finally {
                _releaseReply ($in);
            }
  } // enregistrerVTR

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MAV/SRV:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _SRVStub
