package MAV;


/**
* MAV/CandidatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 36 CEST
*/

public interface CandidatOperations 
{
  int id ();
  String nom ();
  String prenom ();
  String description ();
} // interface CandidatOperations
