package MAV;


/**
* MAV/CandidatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idls/MAV.idl
* lundi 28 mai 2007 15 h 21 CEST
*/

public interface CandidatOperations 
{
  int id ();
  String nom ();
  String prenom ();
  String description ();
} // interface CandidatOperations
