package MAV;

/**
* MAV/CandidatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 36 CEST
*/

public final class CandidatHolder implements org.omg.CORBA.portable.Streamable
{
  public MAV.Candidat value = null;

  public CandidatHolder ()
  {
  }

  public CandidatHolder (MAV.Candidat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MAV.CandidatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MAV.CandidatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MAV.CandidatHelper.type ();
  }

}
