package MAV;


/**
* MAV/ResultVoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 36 CEST
*/

public interface ResultVoteOperations 
{
  int idBV ();
  String nomBV ();
  int idCanton ();
  String canton ();
  int idCirc ();
  String circonscription ();
  int idDept ();
  String departement ();
  int idCandidat ();
  String nom ();
  String prenom ();
  int nbVote ();
} // interface ResultVoteOperations
