package MAV;

/**
* MAV/ResultVoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idls/MAV.idl
* lundi 28 mai 2007 15 h 21 CEST
*/

public final class ResultVoteHolder implements org.omg.CORBA.portable.Streamable
{
  public MAV.ResultVote value = null;

  public ResultVoteHolder ()
  {
  }

  public ResultVoteHolder (MAV.ResultVote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MAV.ResultVoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MAV.ResultVoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MAV.ResultVoteHelper.type ();
  }

}
