package MAV;


/**
* MAV/ResultVoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idls/MAV.idl
* lundi 28 mai 2007 15 h 21 CEST
*/

public interface ResultVoteOperations 
{
  int idBV ();
  String nomBV ();
  int idCanton ();
  String canton ();
  int idCirc ();
  String circonscription ();
  int idDept ();
  String departement ();
  int idCandidat ();
  String nom ();
  String prenom ();
  int nbVote ();
} // interface ResultVoteOperations
