package MAV;

/**
* MAV/SRVHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 36 CEST
*/

public final class SRVHolder implements org.omg.CORBA.portable.Streamable
{
  public MAV.SRV value = null;

  public SRVHolder ()
  {
  }

  public SRVHolder (MAV.SRV initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MAV.SRVHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MAV.SRVHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MAV.SRVHelper.type ();
  }

}
