package MAV;


/**
* MAV/SRVOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idls/MAV.idl
* lundi 28 mai 2007 15 h 21 CEST
*/

public interface SRVOperations 
{
  MAV.ResultVote[] listeResultat () throws MAV.SRVPackage.InternalErrorException;
  MAV.Candidat[] listeCandidat () throws MAV.SRVPackage.InternalErrorException;
  boolean authMAV (int idMAV, int idBV) throws MAV.SRVPackage.InternalErrorException;
  void authPersonne (int numInsee, String password, int idBV) throws MAV.SRVPackage.BadAuthentificationException, MAV.SRVPackage.AlreadyVoteException, MAV.SRVPackage.InternalErrorException, MAV.SRVPackage.IncorrectBVPersonException;
  boolean vote (int numInsee, String password, int idCandidat, int idBV) throws MAV.SRVPackage.BadAuthentificationException, MAV.SRVPackage.AlreadyVoteException, MAV.SRVPackage.InternalErrorException, MAV.SRVPackage.IncorrectBVPersonException;
  void enregistrerVTR (MAV.VTR vtr);
} // interface SRVOperations
