package MAV;


/**
* MAV/VTROperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idls/MAV.idl
* lundi 28 mai 2007 15 h 21 CEST
*/

public interface VTROperations 
{
  void notifieVTR ();
} // interface VTROperations
