package MAV.SRVPackage;


/**
* MAV/SRVPackage/AlreadyVoteException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idls/MAV.idl
* lundi 28 mai 2007 15 h 21 CEST
*/

public final class AlreadyVoteException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public AlreadyVoteException ()
  {
    super(AlreadyVoteExceptionHelper.id());
  } // ctor

  public AlreadyVoteException (String _reason)
  {
    super(AlreadyVoteExceptionHelper.id());
    reason = _reason;
  } // ctor


  public AlreadyVoteException (String $reason, String _reason)
  {
    super(AlreadyVoteExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class AlreadyVoteException
