package MAV.SRVPackage;

/**
* MAV/SRVPackage/AlreadyVoteExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idls/MAV.idl
* lundi 28 mai 2007 15 h 21 CEST
*/

public final class AlreadyVoteExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public MAV.SRVPackage.AlreadyVoteException value = null;

  public AlreadyVoteExceptionHolder ()
  {
  }

  public AlreadyVoteExceptionHolder (MAV.SRVPackage.AlreadyVoteException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MAV.SRVPackage.AlreadyVoteExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MAV.SRVPackage.AlreadyVoteExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MAV.SRVPackage.AlreadyVoteExceptionHelper.type ();
  }

}
