package MAV.SRVPackage;


/**
* MAV/SRVPackage/AlreadyVote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 27 mars 2007 18 h 57 CEST
*/

public final class AlreadyVote extends org.omg.CORBA.UserException
{
  public String reason = null;

  public AlreadyVote ()
  {
    super(AlreadyVoteHelper.id());
  } // ctor

  public AlreadyVote (String _reason)
  {
    super(AlreadyVoteHelper.id());
    reason = _reason;
  } // ctor


  public AlreadyVote (String $reason, String _reason)
  {
    super(AlreadyVoteHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class AlreadyVote
