package MAV.SRVPackage;

/**
* MAV/SRVPackage/BadAuthentificationExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 36 CEST
*/

public final class BadAuthentificationExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public MAV.SRVPackage.BadAuthentificationException value = null;

  public BadAuthentificationExceptionHolder ()
  {
  }

  public BadAuthentificationExceptionHolder (MAV.SRVPackage.BadAuthentificationException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MAV.SRVPackage.BadAuthentificationExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MAV.SRVPackage.BadAuthentificationExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MAV.SRVPackage.BadAuthentificationExceptionHelper.type ();
  }

}
