package MAV.SRVPackage;


/**
* MAV/SRVPackage/BadAuthentificationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 36 CEST
*/

public final class BadAuthentificationException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public BadAuthentificationException ()
  {
    super(BadAuthentificationExceptionHelper.id());
  } // ctor

  public BadAuthentificationException (String _reason)
  {
    super(BadAuthentificationExceptionHelper.id());
    reason = _reason;
  } // ctor


  public BadAuthentificationException (String $reason, String _reason)
  {
    super(BadAuthentificationExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class BadAuthentificationException
