package MAV.SRVPackage;

/**
* MAV/SRVPackage/BVIncorrectForThisPesonneExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 18 CEST
*/

public final class BVIncorrectForThisPesonneExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public MAV.SRVPackage.BVIncorrectForThisPesonneException value = null;

  public BVIncorrectForThisPesonneExceptionHolder ()
  {
  }

  public BVIncorrectForThisPesonneExceptionHolder (MAV.SRVPackage.BVIncorrectForThisPesonneException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MAV.SRVPackage.BVIncorrectForThisPesonneExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MAV.SRVPackage.BVIncorrectForThisPesonneExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MAV.SRVPackage.BVIncorrectForThisPesonneExceptionHelper.type ();
  }

}
