package MAV.SRVPackage;


/**
* MAV/SRVPackage/BVIncorrectForThisPesonneException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 18 CEST
*/

public final class BVIncorrectForThisPesonneException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public BVIncorrectForThisPesonneException ()
  {
    super(BVIncorrectForThisPesonneExceptionHelper.id());
  } // ctor

  public BVIncorrectForThisPesonneException (String _reason)
  {
    super(BVIncorrectForThisPesonneExceptionHelper.id());
    reason = _reason;
  } // ctor


  public BVIncorrectForThisPesonneException (String $reason, String _reason)
  {
    super(BVIncorrectForThisPesonneExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class BVIncorrectForThisPesonneException
