package MAV.SRVPackage;

/**
* MAV/SRVPackage/BVIncorrectForThisPesonneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 17 CEST
*/

public final class BVIncorrectForThisPesonneHolder implements org.omg.CORBA.portable.Streamable
{
  public MAV.SRVPackage.BVIncorrectForThisPesonne value = null;

  public BVIncorrectForThisPesonneHolder ()
  {
  }

  public BVIncorrectForThisPesonneHolder (MAV.SRVPackage.BVIncorrectForThisPesonne initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MAV.SRVPackage.BVIncorrectForThisPesonneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MAV.SRVPackage.BVIncorrectForThisPesonneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MAV.SRVPackage.BVIncorrectForThisPesonneHelper.type ();
  }

}
