package MAV.SRVPackage;


/**
* MAV/SRVPackage/CandidatSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 36 CEST
*/

abstract public class CandidatSeqHelper
{
  private static String  _id = "IDL:MAV/SRV/CandidatSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, MAV.Candidat[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MAV.Candidat[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = MAV.CandidatHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (MAV.SRVPackage.CandidatSeqHelper.id (), "CandidatSeq", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MAV.Candidat[] read (org.omg.CORBA.portable.InputStream istream)
  {
    MAV.Candidat value[] = null;
    int _len0 = istream.read_long ();
    value = new MAV.Candidat[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = MAV.CandidatHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MAV.Candidat[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      MAV.CandidatHelper.write (ostream, value[_i0]);
  }

}
