package MAV.SRVPackage;


/**
* MAV/SRVPackage/IncorrectBVPersonException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../idls/MAV.idl
* lundi 28 mai 2007 15 h 21 CEST
*/

public final class IncorrectBVPersonException extends org.omg.CORBA.UserException
{
  public String reason = null;

  public IncorrectBVPersonException ()
  {
    super(IncorrectBVPersonExceptionHelper.id());
  } // ctor

  public IncorrectBVPersonException (String _reason)
  {
    super(IncorrectBVPersonExceptionHelper.id());
    reason = _reason;
  } // ctor


  public IncorrectBVPersonException (String $reason, String _reason)
  {
    super(IncorrectBVPersonExceptionHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class IncorrectBVPersonException
