package MAV.SRVPackage;

/**
* MAV/SRVPackage/InternalErrorExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../idls/MAV.idl
* mardi 22 mai 2007 18 h 36 CEST
*/

public final class InternalErrorExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public MAV.SRVPackage.InternalErrorException value = null;

  public InternalErrorExceptionHolder ()
  {
  }

  public InternalErrorExceptionHolder (MAV.SRVPackage.InternalErrorException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MAV.SRVPackage.InternalErrorExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MAV.SRVPackage.InternalErrorExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MAV.SRVPackage.InternalErrorExceptionHelper.type ();
  }

}
